// GENERATED by the webcam catalog pipeline (2026-09-14T23:16:02.513Z) — do not edit by hand.
// Every channelId was verified live against youtube.com at generation time
// (see webcam-build/webcams-manifest.json for the full one-by-one evidence).

export type WebcamRegion =
  | 'middle-east'
  | 'africa'
  | 'europe'
  | 'asia'
  | 'americas'
  | 'oceania'
  | 'space';

export interface WebcamFeed {
  id: string;
  city: string;
  country: string;
  region: WebcamRegion;
  channelHandle: string;
  /** Stable YouTube channel id — the embed uses /embed/live_stream?channel= so
   *  YouTube resolves the channel's CURRENT live stream from the viewer's IP. */
  channelId: string;
}

export const WEBCAM_FEEDS: WebcamFeed[] = [
  { id: "kuwait-city", city: "Kuwait City", country: "Kuwait", region: "middle-east", channelHandle: "/@SourceGlobal", channelId: "UC98W74iwmWXnOMHq0lYeDIw" },
  { id: "conflict-zone-cams", city: "Conflict Zone Cams", country: "Multi", region: "middle-east", channelHandle: "/@intelcamslive", channelId: "UCper-NWj8xdXacSpFtF4Mgg" },
  { id: "doha", city: "Doha", country: "Qatar", region: "middle-east", channelHandle: "/@aljazeeraenglish", channelId: "UCNye-wNBqNL5ZzHSJj3l8Bg" },
  { id: "mecca", city: "Mecca", country: "Saudi Arabia", region: "middle-east", channelHandle: "/@SaudiQuranTv", channelId: "UCos52azQNBgW63_9uDJoPDA" },
  { id: "medina", city: "Medina", country: "Saudi Arabia", region: "middle-east", channelHandle: "/@subhanallahtvofficial", channelId: "UCvVrEPcRhPjpGFMltWAQbXQ" },
  { id: "dubai", city: "Dubai", country: "UAE", region: "middle-east", channelHandle: "/@UinDubai", channelId: "UCW21lGGm2EeaABsldywDz-g" },
  { id: "cairo", city: "Cairo", country: "Egypt", region: "africa", channelHandle: "/@VEILTUNE", channelId: "UCPL8mEVnjDTZ3bcE8MAvWvg" },
  { id: "kenya-safari", city: "Kenya Safari", country: "Kenya", region: "africa", channelHandle: "/@Bushtops", channelId: "UCpYmJpK_TSk8imQsZ8A9LNA" },
  { id: "namibia-waterhole", city: "Namibia Waterhole", country: "Namibia", region: "africa", channelHandle: "/@NamibiaCam", channelId: "UC9X6gGKDv2yhMoofoeS7-Gg" },
  { id: "cape-town", city: "Cape Town", country: "South Africa", region: "africa", channelHandle: "/@TableMountainLiveStream", channelId: "UCLaxio5CTbT1gl5i8FB2-yw" },
  { id: "yerevan", city: "Yerevan", country: "Armenia", region: "europe", channelHandle: "/@yerevanlivestream2065", channelId: "UCYG_AHrHc8VzgzYQIhstnEw" },
  { id: "baku", city: "Baku", country: "Azerbaijan", region: "europe", channelHandle: "/@JaZz_Not_JazZ", channelId: "UC31Qm1T33OZioM_w8wWEaHQ" },
  { id: "sarajevo", city: "Sarajevo", country: "Bosnia and Herzegovina", region: "europe", channelHandle: "/@LiveSarajevo4K", channelId: "UCrk_nl_0APWBYukMck4o9Dw" },
  { id: "prague", city: "Prague", country: "Czechia", region: "europe", channelHandle: "/@SlowTVLive", channelId: "UC3ewP9SczRIGGpDXDQvpPyQ" },
  { id: "tallinn", city: "Tallinn", country: "Estonia", region: "europe", channelHandle: "/@timecapsule3593", channelId: "UCBfU-5DA1et2G3vOvZgiXxw" },
  { id: "helsinki", city: "Helsinki", country: "Finland", region: "europe", channelHandle: "/@PortOfHelsinki", channelId: "UCuaFFNhZkcEg2JjEPvzjzzw" },
  { id: "rovaniemi", city: "Rovaniemi", country: "Finland", region: "europe", channelHandle: "/@apukkaresortrovaniemi", channelId: "UC41lTeDc5XoWjVVfyZW7shA" },
  { id: "marseille", city: "Marseille", country: "France", region: "europe", channelHandle: "/@LiveMarseille-CalanqueSamena", channelId: "UCBPHtwB5-bOR9O8J3H12LYQ" },
  { id: "paris", city: "Paris", country: "France", region: "europe", channelHandle: "/@PARISTVCOM", channelId: "UCjgiKi29C--6aW3pgn0l5JA" },
  { id: "berlin", city: "Berlin", country: "Germany", region: "europe", channelHandle: "/@gKohlbecker", channelId: "UCpR-vq358IEHwt-FgPsEBpA" },
  { id: "hamburg", city: "Hamburg", country: "Germany", region: "europe", channelHandle: "/@wettercomLIVE", channelId: "UC6jWPdcAjGQv52K-vooiIrg" },
  { id: "iceland-aurora", city: "Iceland Aurora", country: "Iceland", region: "europe", channelHandle: "/@TokAir-Iceland", channelId: "UCI1Jb6AiEJslLi-BsS1Cdrg" },
  { id: "dublin", city: "Dublin", country: "Ireland", region: "europe", channelHandle: "/@livefromireland", channelId: "UCXtzCdsTkuBWIrOSuMNvANQ" },
  { id: "amalfi", city: "Amalfi", country: "Italy", region: "europe", channelHandle: "/@AmalfisDream", channelId: "UCR8lADA5V4VUSyu6DmbSI6w" },
  { id: "rome", city: "Rome", country: "Italy", region: "europe", channelHandle: "/@romafivesuites", channelId: "UCDL2IVxAgPI7wybiUlQKrWg" },
  { id: "venice", city: "Venice", country: "Italy", region: "europe", channelHandle: "/@iloveyouvenice", channelId: "UCMpn1qLudF-zb4M4bqxLIbw" },
  { id: "amsterdam", city: "Amsterdam", country: "Netherlands", region: "europe", channelHandle: "/@Now4Rent", channelId: "UCWsoep0hJKhGbYosMeQIyXA" },
  { id: "rotterdam", city: "Rotterdam", country: "Netherlands", region: "europe", channelHandle: "/@RotterdamMakeItHappen", channelId: "UChI_8BTUHgCBT4nI0Yqo6fA" },
  { id: "troms-aurora", city: "Tromsø Aurora", country: "Norway", region: "europe", channelHandle: "/@tromshavnkf-livestreamsent4304", channelId: "UCqutoUlRwHgyVPzV1IRRhtQ" },
  { id: "lisbon", city: "Lisbon", country: "Portugal", region: "europe", channelHandle: "/@AVIA%C3%87%C3%83OTV", channelId: "UC0R-K3crhMX9jzswbmfIORw" },
  { id: "madeira", city: "Madeira", country: "Portugal", region: "europe", channelHandle: "/@MadeiraWebLive", channelId: "UCH_lKz2VXlfLPgYOE3biySg" },
  { id: "porto", city: "Porto", country: "Portugal", region: "europe", channelHandle: "/@WebcamTaxi", channelId: "UC1tBnbs03VJ34oLD8cmJSVw" },
  { id: "bucharest", city: "Bucharest", country: "Romania", region: "europe", channelHandle: "/@CaughtOnCam12", channelId: "UCE5jk2omKe23EUKPJtHlzEg" },
  { id: "moscow", city: "Moscow", country: "Russia", region: "europe", channelHandle: "/@rooftopmusiccam", channelId: "UCT09c0e7oAmpv-RM9UyYjPg" },
  { id: "st-petersburg", city: "St Petersburg", country: "Russia", region: "europe", channelHandle: "/@RealAmbience4k", channelId: "UCe_PlCsOVqYbEJhK9VRp-tA" },
  { id: "bratislava", city: "Bratislava", country: "Slovakia", region: "europe", channelHandle: "/@armchairtravel", channelId: "UCO3TJbHlgOoC-u9-0tcllOQ" },
  { id: "ibiza", city: "Ibiza", country: "Spain", region: "europe", channelHandle: "/@cafedelmar", channelId: "UCha0QKR45iw7FCUQ3-1PnhQ" },
  { id: "malaga", city: "Malaga", country: "Spain", region: "europe", channelHandle: "/@meteo365es", channelId: "UCKCw1qKElfcxE6A1KefdG5A" },
  { id: "stockholm", city: "Stockholm", country: "Sweden", region: "europe", channelHandle: "/@StockholmHD", channelId: "UChMnps0BRm1qF0YEoEo69gw" },
  { id: "jungfrau", city: "Jungfrau", country: "Switzerland", region: "europe", channelHandle: "/@TourTips-Unimog-Reisen", channelId: "UCnQMMDhxjoDqENDrK3c7ehg" },
  { id: "zurich", city: "Zurich", country: "Switzerland", region: "europe", channelHandle: "/@zuricharenalivecameras3821", channelId: "UCdR2rlDFO7WMY9UunV6ISmQ" },
  { id: "kyiv", city: "Kyiv", country: "Ukraine", region: "europe", channelHandle: "/@Inquizex", channelId: "UCuyLmOJb7PVCvx8zbRT9_GQ" },
  { id: "edinburgh", city: "Edinburgh", country: "United Kingdom", region: "europe", channelHandle: "/@woollyjumperfilms", channelId: "UCLqR7wwudU-KtpBQO8gf2Rg" },
  { id: "london", city: "London", country: "United Kingdom", region: "europe", channelHandle: "/@NottingHillGateCam", channelId: "UC4-aIBtpNAPqEcMhAyFN6iQ" },
  { id: "hong-kong", city: "Hong Kong", country: "Hong Kong", region: "asia", channelHandle: "/@shunshunlee", channelId: "UCAyQys2w6IkGrqkJyHe-4sQ" },
  { id: "bali", city: "Bali", country: "Indonesia", region: "asia", channelHandle: "/@Bali_Weather", channelId: "UCjc3XanPPTV1Ar1ec6ElXTg" },
  { id: "kyoto", city: "Kyoto", country: "Japan", region: "asia", channelHandle: "/@kyototouristspotlive", channelId: "UCyVf8FIJ-kFpzUadi7_tgZQ" },
  { id: "mount-fuji", city: "Mount Fuji", country: "Japan", region: "asia", channelHandle: "/@%E9%9D%99%E5%B2%A1%E5%B8%82%E3%81%95%E3%81%A3%E3%81%9F%E5%B3%A0%E3%83%A9%E3%82%A4%E3%83%96%E3%82%AB%E3%83%A1%E3%83%A9", channelId: "UCkUdb6wh-TE9MK7Q2VTE5-A" },
  { id: "osaka", city: "Osaka", country: "Japan", region: "asia", channelHandle: "/@osakalive", channelId: "UCRruWUK0POjg2veibHucffQ" },
  { id: "shinjuku-kabukicho", city: "Shinjuku Kabukicho", country: "Japan", region: "asia", channelHandle: "/@livetokyoshinjukulivech8492", channelId: "UC1kDVgEX2DsE295Bkum_K9Q" },
  { id: "tokyo", city: "Tokyo", country: "Japan", region: "asia", channelHandle: "/@tokyonowlive", channelId: "UCwZTHBzo0fHVEWhydjW9vlQ" },
  { id: "kuala-lumpur", city: "Kuala Lumpur", country: "Malaysia", region: "asia", channelHandle: "/@KLSkylineLive", channelId: "UCfVBWzBee1rnmR8AhT2Esng" },
  { id: "kathmandu", city: "Kathmandu", country: "Nepal", region: "asia", channelHandle: "/@WEBCAMNEPALLIVE-PLACES", channelId: "UCp8FhsgzNmYR6F1HxTDMTvw" },
  { id: "singapore", city: "Singapore", country: "Singapore", region: "asia", channelHandle: "/@DIKIPIDIA", channelId: "UCRoe77UVQ9FHHCS9IlX2WxQ" },
  { id: "busan", city: "Busan", country: "South Korea", region: "asia", channelHandle: "/@gwangan_bridge", channelId: "UC-6aUZjKbYIY0YDWapXUaZg" },
  { id: "seoul", city: "Seoul", country: "South Korea", region: "asia", channelHandle: "/@seoulvibes_live", channelId: "UC2j9YVeDkez-niRM85BsvsA" },
  { id: "taipei", city: "Taipei", country: "Taiwan", region: "asia", channelHandle: "/@taipeitravelofficial", channelId: "UCJLjpq7pTJRbP3vtx0LxB9Q" },
  { id: "bangkok", city: "Bangkok", country: "Thailand", region: "asia", channelHandle: "/@bangkok-360", channelId: "UCXBOD07bL65DJCwOmBIbZcQ" },
  { id: "pattaya", city: "Pattaya", country: "Thailand", region: "asia", channelHandle: "/@SOUTHPATTAYALIVECAM", channelId: "UCOQmNYa1iIDcZl-z6duqCww" },
  { id: "buenos-aires", city: "Buenos Aires", country: "Argentina", region: "americas", channelHandle: "/@PaseosyTurismo", channelId: "UCsXOwro8CHI2FWotcTw1U2w" },
  { id: "rio-de-janeiro", city: "Rio de Janeiro", country: "Brazil", region: "americas", channelHandle: "/@homesinrio3840", channelId: "UChWGYkK0I8U83C0FxAxWy4w" },
  { id: "s-o-paulo", city: "São Paulo", country: "Brazil", region: "americas", channelHandle: "/@S%C3%A3oPauloSkylineCam", channelId: "UCssOUNE0pL0KyhhliSrcYbQ" },
  { id: "banff", city: "Banff", country: "Canada", region: "americas", channelHandle: "/@RimrockResortHotelBanff", channelId: "UC8BTmrQbP-RTbIy9mfHTzTQ" },
  { id: "toronto", city: "Toronto", country: "Canada", region: "americas", channelHandle: "/@TorontoLive4k", channelId: "UC28IT4ghbKO988OzkIfRCbw" },
  { id: "vancouver", city: "Vancouver", country: "Canada", region: "americas", channelHandle: "/@VancouverCityViews", channelId: "UCYky246qWfKe82NLQ9VXbgQ" },
  { id: "santiago", city: "Santiago", country: "Chile", region: "americas", channelHandle: "/@Ledrium", channelId: "UCDMqTaUZsY3ElB4xWpO8tFA" },
  { id: "medell-n", city: "Medellín", country: "Colombia", region: "americas", channelHandle: "/@medayo360", channelId: "UCulbrRGi1vry3h4zMTf1z7g" },
  { id: "mexico-city", city: "Mexico City", country: "Mexico", region: "americas", channelHandle: "/@webcamsdemexico", channelId: "UColBcWm6ybTbQnNuQS8JaKg" },
  { id: "lima", city: "Lima", country: "Peru", region: "americas", channelHandle: "/@MirafloresLimaPeruWebcam", channelId: "UCh3qB8rZ7gxtnquRFeBVRcg" },
  { id: "boston", city: "Boston", country: "United States", region: "americas", channelHandle: "/@thirdpolararch", channelId: "UC7SuJuqGTzT1s0R5gtNum2w" },
  { id: "chicago", city: "Chicago", country: "United States", region: "americas", channelHandle: "/@FOX32Chicago", channelId: "UCFmofUYwZd1Ibf_O3PF71jg" },
  { id: "key-west", city: "Key West", country: "United States", region: "americas", channelHandle: "/@HogsBreathKeyWest", channelId: "UCACzxtAksIzlsuBIiOT_ubw" },
  { id: "las-vegas-strip", city: "Las Vegas Strip", country: "United States", region: "americas", channelHandle: "/@JustinClouse", channelId: "UCXY7E6QRZ1o3n3zHCSr2kEg" },
  { id: "los-angeles-hollywood", city: "Los Angeles — Hollywood", country: "United States", region: "americas", channelHandle: "/@LATimesStudios", channelId: "UC4Rrzu44rIpYtuVit90Kl5w" },
  { id: "miami-beach", city: "Miami Beach", country: "United States", region: "americas", channelHandle: "/@ZeroEight", channelId: "UCmSsdXm7F8CWlOODXSzANsg" },
  { id: "new-orleans", city: "New Orleans", country: "United States", region: "americas", channelHandle: "/@ccclive9401", channelId: "UCsDGR8Jg_pr8IfnrrxR2D6w" },
  { id: "new-york-skyline", city: "New York — Skyline", country: "United States", region: "americas", channelHandle: "/@ms36000", channelId: "UCpb8WxAsZPIwaAsNbbKLzmg" },
  { id: "new-york-times-square", city: "New York — Times Square", country: "United States", region: "americas", channelHandle: "/@fox5ny", channelId: "UCIjSUWHWp6KohfnR5OQTXnQ" },
  { id: "railfan-crossing", city: "Railfan Crossing", country: "United States", region: "americas", channelHandle: "/@VirtualRailfan", channelId: "UCOIkT9bq-1N2BvrsBjhNlag" },
  { id: "san-francisco", city: "San Francisco", country: "United States", region: "americas", channelHandle: "/@KTVUFox2", channelId: "UCVhtkN7-c8mA8GXEoxS4YQw" },
  { id: "seattle", city: "Seattle", country: "United States", region: "americas", channelHandle: "/@fox13seattle", channelId: "UC5bKZHg4PzURMOWcvanl6nA" },
  { id: "waikiki", city: "Waikiki", country: "United States", region: "americas", channelHandle: "/@uberjeph", channelId: "UCgexA0gpQd9I_Y3eHGwJDKw" },
  { id: "washington-dc", city: "Washington DC", country: "United States", region: "americas", channelHandle: "/@fox5dc", channelId: "UCHLyP4MuA-JAFBCwxXOEDdA" },
  { id: "yellowstone", city: "Yellowstone", country: "United States", region: "americas", channelHandle: "/@cookecitysinclair4110", channelId: "UCj6SYxnysC3Vbt522AdqKOw" },
  { id: "melbourne", city: "Melbourne", country: "Australia", region: "oceania", channelHandle: "/@CityscapeLive", channelId: "UC6Au7oIglvHInniXAQSW7iQ" },
  { id: "sydney-harbour", city: "Sydney Harbour", country: "Australia", region: "oceania", channelHandle: "/@webcamsydney", channelId: "UCLav_kTu9PmAEChvGyrPbhQ" },
  { id: "auckland", city: "Auckland", country: "New Zealand", region: "oceania", channelHandle: "/@AucklandCityViews", channelId: "UCnuF5fiEc6DdbhDHCQoCAfA" },
  { id: "wellington", city: "Wellington", country: "New Zealand", region: "oceania", channelHandle: "/@wlgwetaworker", channelId: "UCCEo1hxcfQe7p-odS5pEZxg" },
  { id: "hawaii-north-shore", city: "Hawaii — North Shore", country: "United States", region: "oceania", channelHandle: "/@ExploreBigSurfandBeaches", channelId: "UCJRuk-FJ6dzX0MOpnd0UDCg" },
  { id: "earth-from-space", city: "Earth from Space", country: "Space", region: "space", channelHandle: "/@Sen", channelId: "UCkvW_7kp9LJrztmgA4q4bJQ" },
  { id: "iss-earth-view", city: "ISS Earth View", country: "Space", region: "space", channelHandle: "/@tripwebcam", channelId: "UCEJ3VXhzw2ykC34059F_-cw" },
  { id: "nasa-live", city: "NASA Live", country: "Space", region: "space", channelHandle: "/@NASASpaceflight", channelId: "UCSUu1lih2RifWkKtDOJdsBA" },
];
